# Generated by Django 4.2.4 on 2023-09-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanoma_detection_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='imagen',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
