# Generated by Django 4.2.4 on 2023-09-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanoma_detection_app', '0004_alter_detecciones_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosdetecciones',
            name='es_favorito',
            field=models.BooleanField(default=False),
        ),
    ]
