# Generated by Django 4.2.4 on 2023-10-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanoma_detection_app', '0006_detecciones_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionusuario',
            name='tema_preferido',
            field=models.BooleanField(default=False),
        ),
    ]
