# Generated by Django 4.2.4 on 2023-10-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanoma_detection_app', '0007_alter_configuracionusuario_tema_preferido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionusuario',
            name='notificaciones_habilitadas',
            field=models.BooleanField(default=True),
        ),
    ]
