# Generated by Django 4.2.4 on 2023-10-09 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melanoma_detection_app', '0008_alter_configuracionusuario_notificaciones_habilitadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
