# Generated by Django 4.2.4 on 2023-10-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanoma_detection_app', '0010_remove_notificaciones_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
